# <>------------<>
# <   Shipment   >
# <>------------<>
shipment:
  # Must be a valid day of week, from 1-7
  # 1 being monday, 7 being sunday
  day-of-week: 7

  # How often shipments are automatically saved (in minutes)
  # Set to -1 to only save shipments on server closing
  auto-save: 5

  # If set to true, items can still be edited (added/removed) on the day of the shipment
  # Otherwise, only future shipments will be editable
  real-time-editing: true

# <>------------<>
# < Item Presets >
# <>------------<>
# When a new upcoming shipment is created, should it be auto populated
# with items as defined by an 'item preset' (a saved set of items from a
# previous shipment)
presets:
  enabled: true

  # If there are multiple presets, should a random preset be chosen and applied
  random: true

  # The name for the default preset to be applied (if random preset is false)
  default: ''

# <>------------<>
# <   The Ship   >
# <>------------<>
# The name of the schematic to load in the 'schematics' folder
# Do not include file extension in this name
ship-schematic-name: 'ship'
ship-schematic-extension: 'schem'

# The world to spawn the ship in
ship-world: 'world'

# Setting y to -1 will stop the ship from spawning
ship-location:
  x: 0
  y: -1
  z: 0

# <>------------<>
# <   The  NPC   >
# <>------------<>
# Please setup the NPC using Citizens.
# Once setup, add the NPCs id to the list
# Use '/npc id' to view the NPCs id
npc-ids:
  - -1

# If there are no items on sale for the next week,
# should the buy GUI not show when clicking on the NPC
# This will skip shipments that have not been setup
npc-skip-empty-shipments: true

# <>------------<>
# <    Ticket    >
# <>------------<>
# The maximum amount of tickets a single player can buy per shipment
# Set to -1 for infinite
max-tickets-per-player-per-shipment: 1

# If set to true, all ticket purchases will be output to the console
output-ticket-purchases: false

# Send a warning message to console if a player tries to open a duplicate ticket
warn-duplicate-tickets: true

# If true, only the player that purchased the ticket can claim its items
only-purchaser-can-claim: true

# <>------------<>
# <    Crates    >
# <>------------<>
# When pasting the schematic, should this plugin scan the region
# for the specified crate blocks to automatically register them?
auto-register-crates: true

# See list of valid materials here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
crate-materials:
  - 'CHEST'
  - 'BARREL'

# Using holographic displays, should this plugin
# display a message above the crates?
use-holographic-displays: true

# Message displayed above crates
holographic-display:
  - '&3Crate'

# Hologram is originally centered at X.5, Y, Z.5
# Offsets relative to prior values
hologram-offset:
  x: 0
  y: 1
  z: 0

crate-effects:
  # See list of valid sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sound:
    play: true
    on-open: 'BLOCK_CHEST_OPEN'
    volume: 1.0
    pitch: 1.0